name: home  # アプリケーションの名前
description: A new Flutter project.  # アプリケーションの説明
publish_to: 'none'  # アプリケーションをpub.devに公開しない設定
version: 1.0.0+1  # アプリケーションのバージョン

environment:  # Dartのバージョン
  sdk: '>=3.0.2 <4.0.0'

dependencies:  # アプリケーションが依存するパッケージ
  flutter:  # Flutter SDK
    sdk: flutter
  flutter_datetime_picker: ^1.5.1  # 日付と時間のピッカー
  firebase_auth: ^4.6.3  # Firebase Auth（Firebaseの認証機能）
  cloud_firestore: ^4.8.1  # Cloud Firestore（Firebaseのデータベース）
  cupertino_icons: ^1.0.2  # Cupertino Icons（iOSスタイルのアイコン）
  firebase_core: ^2.14.0  # Firebase Core（Firebaseの基本機能）
  carousel_slider: ^4.2.1  # Carousel Slider（カルーセルスライダー）
  image_picker: ^0.8.9  # Image Picker（画像選択）
  firebase_storage: ^11.2.3  # Firebase Storage（Firebaseのストレージ）
  url_launcher: ^6.1.12 # Url_Launcher （アプリ内でブラウザを開く）
  holiday_jp: ^0.0.8 # 日本の祝日
  shared_preferences: ^2.2.0 # ログイン状態の永続化
  flutter_svg: ^2.0.7 # svgをアイコンとして利用する
  http: ^1.1.0 #スクレイピング用
  html: ^0.15.4 #スクレイピング用
  flutter_rating_bar: ^4.0.1 #食堂メニューの評価
  crypto: ^3.0.3 #メニュー名をハッシュ化して一意なドキュメントIDにするために追加

dev_dependencies:  # 開発時に依存するパッケージ
  flutter_test:  # Flutterのテストフレームワーク
    sdk: flutter
  intl: ^0.18.1  # 日付と時間のフォーマット
  flutter_lints: ^2.0.0  # Flutterの推奨されるリントルール
  flutter_native_splash: ^2.3.1 #アプリ起動時のアイコン表示関連

flutter_native_splash:
  color: '#ed6102'
  image: 'assets/ic_launcher_foreground.png'
  color_dark: '#000000'
  image_dark: 'assets/ic_launcher_foreground.png'
  fullscreen: true
  android_12:
    icon_background_color: '#ed6102'
    image: 'assets/ic_launcher_foreground.png'
    icon_background_color_dark: '#000000'
    image_dark: 'assets/ic_launcher_foreground.png'

flutter:  # Flutterの設定
  uses-material-design: true  # Material Iconsを使用する設定
  assets:  # アプリケーションのアセット（画像やフォントなど）
    - assets/
  fonts:  # アプリケーションのフォント
    - family: TabLogo
      fonts:
        - asset: fonts/TabLogo.ttf
    - family: Zen_Kaku_Gothic_New
      fonts:
        - asset: fonts/Zen_Kaku_Gothic_New/ZenKakuGothicNew-Light.ttf
          weight: 300
        - asset: fonts/Zen_Kaku_Gothic_New/ZenKakuGothicNew-Regular.ttf
          weight: 400
        - asset: fonts/Zen_Kaku_Gothic_New/ZenKakuGothicNew-Medium.ttf
          weight: 500
        - asset: fonts/Zen_Kaku_Gothic_New/ZenKakuGothicNew-Bold.ttf
        - asset: fonts/Zen_Kaku_Gothic_New/ZenKakuGothicNew-Bold.ttf
          weight: 700
        - asset: fonts/Zen_Kaku_Gothic_New/ZenKakuGothicNew-Black.ttf
          weight: 900
